VMCODE1(VM_PUSHCONST, PushConstInt)
VMCODE2(VM_PUSHCONSTFLOAT, PushConstFloat)
VMCODE1(VM_PUSHSTRING, PushString)
VMCODE1(VM_PUSHVALUEREF, PushGlobalValueRef)
VMCODE1(VM_PUSHLOCALREF, PushLocalRef)
VMCODE1(VM_PUSHMEMBERREF, PushMemberRef)
VMCODE1(VM_PUSHARRAYREF, PushGlobalArrayRef)
VMCODE1(VM_PUSHLOCALARRAYREF, PushLocalArrayRef)
VMCODE1(VM_PUSHVALUE, PushGlobalValue)
VMCODE1(VM_PUSHLOCAL, PushLocal)
VMCODE1(VM_PUSHMEMBER, PushMember)
VMCODE1(VM_PUSHARRAY, PushGlobalArray)
VMCODE1(VM_PUSHLOCALARRAY, PushLocalArray)
VMCODE1(VM_PUSHADDR, PushAddr)
VMCODE0(VM_PUSHNULL, PushNull)
VMCODE1(VM_PUSHARRAYADDR, PushArrayAddr)
VMCODE1(VM_POPVALUE, PopValue)
VMCODE1(VM_POPLOCAL, PopLocal)
VMCODE1(VM_POPMEMBER, PopMember)
VMCODE1(VM_POPMEMBERVALUETYPE, PopMemberValueType)
VMCODE1(VM_POPMEMBERREF, PopMemberRef)
VMCODE1(VM_POPARRAY, PopArray)
VMCODE1(VM_POPLOCALARRAY, PopLocalArray)
VMCODE1(VM_POPLOCALREF, PopLocalRef)
VMCODE1(VM_POPLOCALARRAYREF, PopLocalArrayRef)
VMCODE1(VM_ALLOCSTACK, OpAllocStack)
VMCODE1(VM_ENUMALLOCSTACK, OpAllocStackEnumType)
VMCODE1(VM_ALLOCSTACKSCRIPTTYPE, OpAllocStack_ScriptType)
VMCODE1(VM_ALLOCSTACKFUNCTIONTYPE, OpAllocStackFunctionType)
VMCODE1(VM_ALLOCSTACKREF, OpAllocStack_Ref)
VMCODE1(VM_ALLOCSTACKREFENUMTYPE, OpAllocStack_Ref_EnumType)
VMCODE1(VM_ALLOCSTACKREFSCRIPTTYPE, OpAllocStack_Ref_ScriptType)
VMCODE1(VM_ALLOCSTACKREFFUNCTIONTYPE, OpAllocStack_Ref_FunctionType)
VMCODE0(VM_POP, OpPop)
VMCODE_T(VM_NEG, OpNeg)
VMCODE_T(VM_NOT, OpNot)
VMCODE_T0(VM_NEGINT, OpNeg, std::int32_t)
VMCODE_T0(VM_NOTINT, OpNot, std::int32_t)
VMCODE_T0(VM_NEGFLOAT, OpNeg, float)
VMCODE_T0(VM_NOTFLOAT, OpNot, float)
VMCODE_T0(VM_NEGVEC2, OpNeg, ButiEngine::Vector2)
VMCODE_T0(VM_NEGVEC3, OpNeg, ButiEngine::Vector3)
VMCODE_T0(VM_NEGVEC4, OpNeg, ButiEngine::Vector4)
VMCODE_T0(VM_NEGMAT4, OpNeg, ButiEngine::Matrix4x4)
VMCODE_TU(VM_CAST, OpCast)
VMCODE_TU0(VM_CASTINTFLOAT, OpCast, std::int32_t, float)
VMCODE_TU0(VM_CASTFLOATINT, OpCast, float, std::int32_t)
VMCODE_T(VM_INC, OpIncrement)
VMCODE_T(VM_DEC, OpDecrement)
VMCODE_T0(VM_INCINT, OpIncrement, std::int32_t)
VMCODE_T0(VM_DECINT, OpDecrement, std::int32_t)
VMCODE_T0(VM_INCFLOAT, OpIncrement, float)
VMCODE_T0(VM_DECFLOAT, OpDecrement, float)
VMCODE_TU(VM_EQ, OpEq)
VMCODE_TU0(VM_EQINT, OpEq, std::int32_t, std::int32_t)
VMCODE_TU0(VM_EQINTFLOAT, OpEq, std::int32_t, float)
VMCODE_TU0(VM_EQFLOAT, OpEq, float, float)
VMCODE_TU0(VM_EQFLOATINT, OpEq, float,std::int32_t)
VMCODE_TU0(VM_EQVEC2, OpEq, ButiEngine::Vector2, ButiEngine::Vector2)
VMCODE_TU0(VM_EQVEC3, OpEq, ButiEngine::Vector3, ButiEngine::Vector3)
VMCODE_TU0(VM_EQVEC4, OpEq, ButiEngine::Vector4, ButiEngine::Vector4)
VMCODE_TU0(VM_EQMAT4, OpEq, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4)
VMCODE_TU(VM_NE, OpNe)
VMCODE_TU0(VM_NEINT, OpNe, std::int32_t, std::int32_t)
VMCODE_TU0(VM_NEINTFLOAT, OpNe, std::int32_t, float)
VMCODE_TU0(VM_NEFLOAT, OpNe, float, float)
VMCODE_TU0(VM_NEFLOATINT, OpNe, float,std::int32_t)
VMCODE_TU0(VM_NEVEC2, OpNe, ButiEngine::Vector2,ButiEngine::Vector2)
VMCODE_TU0(VM_NEVEC3, OpNe, ButiEngine::Vector3, ButiEngine::Vector3)
VMCODE_TU0(VM_NEVEC4, OpNe, ButiEngine::Vector4, ButiEngine::Vector4)
VMCODE_TU0(VM_NEMAT4, OpNe, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4)
VMCODE_TU(VM_GT, OpGt)
VMCODE_TU(VM_GE, OpGe)
VMCODE_TU(VM_LT, OpLt)
VMCODE_TU(VM_LE, OpLe)
VMCODE_TU0(VM_GTINT, OpGt, int, int)
VMCODE_TU0(VM_GTFLOAT, OpGt, float, float)
VMCODE_TU0(VM_GTINTFLOAT, OpGt, int, float)
VMCODE_TU0(VM_GTFLOATINT, OpGt, float, int)
VMCODE_TU0(VM_GEINT, OpGe, int, int)
VMCODE_TU0(VM_GEFLOAT, OpGe, float, float)
VMCODE_TU0(VM_GEINTFLOAT, OpGe, int, float)
VMCODE_TU0(VM_GEFLOATINT, OpGe, float, int)
VMCODE_TU0(VM_LTINT, OpLt, int, int)
VMCODE_TU0(VM_LTFLOAT, OpLt, float, float)
VMCODE_TU0(VM_LTINTFLOAT, OpLt, int, float)
VMCODE_TU0(VM_LTFLOATINT, OpLt, float, int)
VMCODE_TU0(VM_LEINT, OpLe, int, int)
VMCODE_TU0(VM_LEFLOAT, OpLe, float, float)
VMCODE_TU0(VM_LEINTFLOAT, OpLe, int, float)
VMCODE_TU0(VM_LEFLOATINT, OpLe, float, int)
VMCODE0(VM_LOGAND, OpLogAnd)
VMCODE0(VM_LOGOR, OpLogOr)
VMCODE0(VM_AND, OpAnd)
VMCODE0(VM_OR, OpOr)
VMCODE0(VM_LSHIFT, OpLeftShift)
VMCODE0(VM_RSHIFT, OpRightShift)
VMCODE_TUV(VM_ADD, OpAdd)
VMCODE_TUV(VM_SUB, OpSub)
VMCODE_TUV(VM_MUL, OpMul)
VMCODE_TUV(VM_DIV, OpDiv)
VMCODE_TU(VM_MOD, OpMod)
VMCODE_TUV0(VM_ADDINT, OpAdd, std::int32_t, std::int32_t, std::int32_t)
VMCODE_TUV0(VM_SUBINT, OpSub, std::int32_t, std::int32_t, std::int32_t)
VMCODE_TUV0(VM_MULINT, OpMul, std::int32_t, std::int32_t, std::int32_t)
VMCODE_TUV0(VM_DIVINT, OpDiv, std::int32_t, std::int32_t, std::int32_t)
VMCODE_TU0(VM_MODINT, OpMod, std::int32_t, std::int32_t)
VMCODE_TUV0(VM_ADDFLOAT, OpAdd, float, float,float)
VMCODE_TUV0(VM_SUBFLOAT, OpSub, float, float,float)
VMCODE_TUV0(VM_MULFLOAT, OpMul, float, float,float)
VMCODE_TUV0(VM_DIVFLOAT, OpDiv, float, float,float)
VMCODE_TU0(VM_MODFLOAT, OpMod, float, float)
VMCODE_TUV0(VM_ADDINTFLOAT, OpAdd, std::int32_t, float,float)
VMCODE_TUV0(VM_SUBINTFLOAT, OpSub, std::int32_t, float,float)
VMCODE_TUV0(VM_MULINTFLOAT, OpMul, std::int32_t, float,float)
VMCODE_TUV0(VM_DIVINTFLOAT, OpDiv, std::int32_t, float,float)
VMCODE_TU0(VM_MODINTFLOAT, OpMod, std::int32_t, float)
VMCODE_TUV0(VM_ADDFLOATINT, OpAdd, float, int,float)
VMCODE_TUV0(VM_SUBFLOATINT, OpSub, float, int,float)
VMCODE_TUV0(VM_MULFLOATINT, OpMul, float, int,float)
VMCODE_TUV0(VM_DIVFLOATINT, OpDiv, float, int,float)
VMCODE_TU0(VM_MODFLOATINT, OpMod, float, int)
VMCODE_TUV0(VM_ADDVEC2, OpAdd, ButiEngine::Vector2, ButiEngine::Vector2, ButiEngine::Vector2)
VMCODE_TUV0(VM_SUBVEC2, OpSub, ButiEngine::Vector2, ButiEngine::Vector2, ButiEngine::Vector2)
VMCODE_TUV0(VM_MULVEC2, OpMul, ButiEngine::Vector2, ButiEngine::Vector2, ButiEngine::Vector2)
VMCODE_TUV0(VM_DIVVEC2, OpDiv, ButiEngine::Vector2, ButiEngine::Vector2, ButiEngine::Vector2)
VMCODE_TUV0(VM_MULVEC2INT, OpMul, ButiEngine::Vector2, std::int32_t, ButiEngine::Vector2)
VMCODE_TUV0(VM_DIVVEC2INT, OpDiv, ButiEngine::Vector2, std::int32_t, ButiEngine::Vector2)
VMCODE_TUV0(VM_MULVEC2FLOAT, OpMul, ButiEngine::Vector2, float, ButiEngine::Vector2)
VMCODE_TUV0(VM_DIVVEC2FLOAT, OpDiv, ButiEngine::Vector2, float, ButiEngine::Vector2)
VMCODE_TUV0(VM_MULINTVEC2, OpMul, std::int32_t, ButiEngine::Vector2, ButiEngine::Vector2)
VMCODE_TUV0(VM_MULFLOATVEC2, OpMul, float, ButiEngine::Vector2, ButiEngine::Vector2)
VMCODE_TUV0(VM_ADDVEC3, OpAdd, ButiEngine::Vector3, ButiEngine::Vector3, ButiEngine::Vector3)
VMCODE_TUV0(VM_SUBVEC3, OpSub, ButiEngine::Vector3, ButiEngine::Vector3, ButiEngine::Vector3)
VMCODE_TUV0(VM_MULVEC3, OpMul, ButiEngine::Vector3, ButiEngine::Vector3, ButiEngine::Vector3)
VMCODE_TUV0(VM_DIVVEC3, OpDiv, ButiEngine::Vector3, ButiEngine::Vector3, ButiEngine::Vector3)
VMCODE_TUV0(VM_MULVEC3INT, OpMul, ButiEngine::Vector3, std::int32_t, ButiEngine::Vector3)
VMCODE_TUV0(VM_DIVVEC3INT, OpDiv, ButiEngine::Vector3, std::int32_t, ButiEngine::Vector3)
VMCODE_TUV0(VM_MULVEC3FLOAT, OpMul, ButiEngine::Vector3, float, ButiEngine::Vector3)
VMCODE_TUV0(VM_DIVVEC3FLOAT, OpDiv, ButiEngine::Vector3, float, ButiEngine::Vector3)
VMCODE_TUV0(VM_MULINTVEC3, OpMul, std::int32_t, ButiEngine::Vector3, ButiEngine::Vector3)
VMCODE_TUV0(VM_MULFLOATVEC3, OpMul, float, ButiEngine::Vector3, ButiEngine::Vector3)
VMCODE_TUV0(VM_ADDVEC4, OpAdd, ButiEngine::Vector4, ButiEngine::Vector4, ButiEngine::Vector4)
VMCODE_TUV0(VM_SUBVEC4, OpSub, ButiEngine::Vector4, ButiEngine::Vector4, ButiEngine::Vector4)
VMCODE_TUV0(VM_MULVEC4, OpMul, ButiEngine::Vector4, ButiEngine::Vector4, ButiEngine::Vector4)
VMCODE_TUV0(VM_DIVVEC4, OpDiv, ButiEngine::Vector4, ButiEngine::Vector4, ButiEngine::Vector4)
VMCODE_TUV0(VM_MULVEC4INT, OpMul, ButiEngine::Vector4, std::int32_t, ButiEngine::Vector4)
VMCODE_TUV0(VM_DIVVEC4INT, OpDiv, ButiEngine::Vector4, std::int32_t, ButiEngine::Vector4)
VMCODE_TUV0(VM_MULVEC4FLOAT, OpMul, ButiEngine::Vector4, float, ButiEngine::Vector4)
VMCODE_TUV0(VM_DIVVEC4FLOAT, OpDiv, ButiEngine::Vector4, float, ButiEngine::Vector4)
VMCODE_TUV0(VM_MULINTVEC4, OpMul, std::int32_t, ButiEngine::Vector4, ButiEngine::Vector4)
VMCODE_TUV0(VM_MULFLOATVEC4, OpMul, float, ButiEngine::Vector4, ButiEngine::Vector4)
VMCODE_TUV0(VM_ADDMAT4, OpAdd, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4)
VMCODE_TUV0(VM_SUBMAT4, OpSub, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4)
VMCODE_TUV0(VM_MULMAT4, OpMul, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4)
VMCODE_TUV0(VM_MULMAT4INT, OpMul, ButiEngine::Matrix4x4, std::int32_t, ButiEngine::Matrix4x4)
VMCODE_TUV0(VM_MULMAT4FLOAT, OpMul, ButiEngine::Matrix4x4, float, ButiEngine::Matrix4x4)
VMCODE_TUV0(VM_MULINTMAT4, OpMul, std::int32_t, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4)
VMCODE_TUV0(VM_MULFLOATMAT4, OpMul, float, ButiEngine::Matrix4x4, ButiEngine::Matrix4x4)
VMCODE_TUV0(VM_MULMAT4VEC3, OpMul, ButiEngine::Matrix4x4, ButiEngine::Vector3, ButiEngine::Vector3)
VMCODE_TUV0(VM_MULMAT4VEC4, OpMul, ButiEngine::Matrix4x4, ButiEngine::Vector4, ButiEngine::Vector4)
VMCODE_TUV0(VM_MULVEC3MAT4, OpMul, ButiEngine::Vector3, ButiEngine::Matrix4x4, ButiEngine::Vector3)
VMCODE_TUV0(VM_MULVEC4MAT4, OpMul, ButiEngine::Vector4, ButiEngine::Matrix4x4, ButiEngine::Vector4)
VMCODE0(VM_STREQ, OpStrEq)
VMCODE0(VM_STRNE, OpStrNe)
VMCODE0(VM_STRGT, OpStrGt)
VMCODE0(VM_STRGE, OpStrGe)
VMCODE0(VM_STRLT, OpStrLt)
VMCODE0(VM_STRLE, OpStrLe)
VMCODE0(VM_STRADD, OpStrAdd)
VMCODE1(VM_JMP, OpJmp)
VMCODE1(VM_JMPC, OpJmpC)
VMCODE1(VM_JMPNC, OpJmpNC)
VMCODE1(VM_TEST, OpTest)
VMCODE1(VM_CALL, OpCall)
VMCODE0(VM_CALLBYVARIABLE, OpCallByVariable)
VMCODE1(VM_PUSHFUNCTIONOBJECT, OpPushFunctionAddress)
VMCODE1(VM_PUSHRAMDA, OpPushLambda)
VMCODE1(VM_SYSCALL, OpSysCall)
VMCODE1(VM_SYSCALLMETHOD, OpSysMethodCall)
VMCODE0(VM_RETURN, OpReturn)
VMCODE0(VM_RETURNV, OpReturnV)
VMCODE0(VM_HALT, OpHalt)

